### ISSUE TITLE
fix covariance matrix for MCMC

### ISSUE THREAD

**Issue by kilianbreathnach** [mjvakili/ccppabc#10]
need a flexible way of building and loading inverse covariance matrices for emcee analyses, this includes changes to data.py

**Comment by changhoonhahn** [comment]
I'm not sure I understand what you mean by this. Technically, all of our observables have to recomputed, not just the covariance matrices for emcee. I purposely made it inflexible so that the observables are consistent with the covariance matrices and vice versa.

**Comment by kilianbreathnach** [comment]
I mean building a covariance matrix out of the heterogeneous data vector for whatever combined observables are being used, i.e. including nbar AND gmf, or nbar and gmf AND xi in the full covariance matrix. I have this started and will push a new script with an example of this soon, though I am uncertain how to include the factor for unbiased estimation of tpcf in a full covariance matrix

**Comment by mjvakili** [comment]
Refer to this BOSS paper for discussion of un-biased covariance matrix:

http://arxiv.org/abs/1312.4899

**Comment by changhoonhahn** [comment]
I see. So you mean a covariance matrix that takes into account the
covariance between different observables (e.g. nbar and xi). Yes, this
needs to be implemented.
