### ISSUE TITLE
Gelman-rubin test for convergence of mcmc chains

### ISSUE THREAD

**Issue by mjvakili** [mjvakili/ccppabc#11]
I need to implement this in the code.

**Comment by davidwhogg** [comment]
Can you point me to the implementation in the code?

**Comment by mjvakili** [comment]
Oh, I totally forgot to push the file itself! Will do this in a minute.

**Comment by mjvakili** [comment]
@davidwhogg : This is the implementation:
https://github.com/mjvakili/ccppabc/blob/master/halo/code/grtest.py
