### ISSUE TITLE
pyfof ImportError

### ISSUE THREAD

**Issue by changhoonhahn** [mjvakili/ccppabc#13]
When I run abcpmc_restart.py on mercer, I get the following ImportError: 

`Traceback (most recent call last):  File "abcpmc_restart.py", line 31, in <module> `
`    import data_multislice as Data`
`  File "/home/chh327/project/ccppabc/halo/code/data_multislice.py", line 9, in <module>`
`    import pyfof`
`ImportError: dlopen: cannot load any more object with static TLS`

I'm not sure what's causing this but I think it might be a good opportunity to do a thorough code review and do a planned submission of all the runs we need for the paper. @mjvakili

**Comment by mjvakili** [comment]
Did you chang all the paths to directories in the .ps file to your local installations?
That has to do with the settings of mercer. You may want to send this to Shenglong as well.
Yes, code review sounds good.

**Comment by changhoonhahn** [comment]
Yeah, it's definitely not an issue with the paths. 

I'll send an email to Shenglong.
