### ISSUE TITLE
tex: Section 3.4 (page 8)

### ISSUE THREAD

**Issue by changhoonhahn** [mjvakili/ccppabc#19]
@mjvakili , in the discussion of Figure 7, 8 in Section 3.4, I'm not sure how meaningful it is to provide a detailed comparison of slight discrepancies between the ABC and Gaussian pseudo-likelihood posterior PDFs.

**Comment by mjvakili** [comment]
@changhoonhahn : I agree. At least in discussion of Figure 7, we don't need to describe the slight differences between the posterior probabilities. They're very consistent! But in discussion of Figure 8, perhaps we should point out that the marginalized distribution over alpha is skewed towards smaller values of alpha when we use a Gaussian pseudo-likelihood!

**Comment by changhoonhahn** [comment]
@mjvakili : Right, after looking at Figures 7 and 8 again, I think perhaps the discrepancies in alpha are worth mentioning in the text. I'll incorporate them in.

**Comment by changhoonhahn** [comment]
@mjvakili : Can you check out the latest push. I've included text description of the Figure 7, 8, 9, and 10, which describes the discrepancies in alpha? If you like it close this issue.

**Comment by mjvakili** [comment]
@changhoonhahn : I read it! It looks good to me.
