### ISSUE TITLE
Group finders

### ISSUE THREAD

**Issue by mjvakili** [mjvakili/ccppabc#2]
Let's read and understand the relevance of this paper (and important references therein) to our group multiplicity function stuff:

http://arxiv.org/abs/1505.04798

**Comment by changhoonhahn** [comment]
I've just skimmed the paper, but I don't think we should draw too much focus on the group finder we use. It's an interesting paper for sure, but I don't think we should be so interested in the benchmarking of these group finders in retrieving measurements such as galaxy conformity or central/satellite fractions. 

We're really not trying to do anything beyond demonstrating that we can add observables without a simple likelihood calculation that is not independent with other observables. Our GMF is entirely constrained within the group finder we use and not an interpretable measurement.

**Comment by mjvakili** [comment]
Yes, that's a fair point. We are not trying to interpret the performance of group finder measurements---in terms of their compatibility with the halos---we are only interested in using them to measure GMF as a tool for constraining HOD.

That being said, it might be helpful to mention these things briefly at some point in the discussion section.

**Comment by kilianbreathnach** [comment]
I'll give it an in-depth read and pick out points for our discussion, I've
been digging through the assembly bias literature anyway so this paper is
on my list.

**Comment by mjvakili** [comment]
Sweet! thanks Kilian.
