### ISSUE TITLE
tex: Section 3.4 (advantages of ABC for systematics)

### ISSUE THREAD

**Issue by changhoonhahn** [mjvakili/ccppabc#21]
@mjvakili : I incorporated the sentence you added for the advantages of ABC in accounting for systematics (Section 3.4 Page 10). I added some citations to systematics papers in BOSS. Can you check out the updated paragraph and confirm the changes?

**Comment by mjvakili** [comment]
Looks great!

**Comment by changhoonhahn** [comment]
@mjvakili : dude, you gotta cool it with the exclamation points. I know you're not that excited about every single edit.
