### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by mjvakili** [mjvakili/ccppabc#23]
@changhoonhahn : just a reminder to remove the 2PCF from this line:

https://github.com/mjvakili/ccppabc/blob/master/ccppabc/text/revision/main.tex#L91

**Comment by changhoonhahn** [comment]
Removed and edited.

**Comment by mjvakili** [comment]
Super minor comment: 
There is ambiguity in "it" in this line: 
https://github.com/mjvakili/ccppabc/blob/master/ccppabc/text/revision/main.tex#L96
Does it refer to likelihood free inferences? ABC?

Let's change it to ABC

**Comment by changhoonhahn** [comment]
sounds good.
