### ISSUE TITLE
Response to the referee

### ISSUE THREAD

**Issue by mjvakili** [mjvakili/ccppabc#24]
@changhoonhahn : could you read what's added to the response to the referee report and edit it?

**Comment by changhoonhahn** [comment]
@mjvakili : I've made some major edits to the referee report response. Can you read through them? 

For Major Comment #2, I don't think the response you drafted answers the referee's comment appropriately. They are more appropriate for answering comment #1. 

For Major Comment #4, did you write something up? If so, it's not there in reflected in the referee_report.md

**Comment by changhoonhahn** [comment]
@mjvakili : Also, in the abstract, we do *not* say 
> that an incorrect form of the likelihood function can lead to biased parameter inference
So I have removed that from the response to Ref Report Comment #1.

**Comment by changhoonhahn** [comment]
@mjvakili : I've added responses to comments 2 and 4. I don't think we've addressed the referee's comments very comprehensively, but perhaps it's sufficient -- especially since it's due tomorrow!

**Comment by mjvakili** [comment]
@changhoonhahn Ok great. Let me go through them again

**Comment by mjvakili** [comment]
@changhoonhahn : The response to the referee looks very concise but that should be okay since the changes made in the text are comprehensive. 
I think this looks good.

**Comment by davidwhogg** [comment]
My only advice is to be very nice to the referee.
