### ISSUE TITLE
ConstEps in code/abc_pemcee.py

### ISSUE THREAD

**Issue by changhoonhahn** [mjvakili/ccppabc#3]
@mjvakili In abc_pemcee.py line 87 you call the ConstEps module from abcpmc. What does this do exactly? Does this keep the threshold eps the same for every iteration or is this a 75th percentile threshold ?

It was originally hardcoded with [1e13, 1e13] (commented out on line 86), I'm guessing that this was for testing purposes?

**Comment by mjvakili** [comment]
ConstEps module intializes the tolerance to some number. In the next iterations, we change it to 75% quantile (50% quantile in the fitst 2 iterations) of the distances in the previous iterations. In principle, you could keep it constant. But we manually change it to whatever we want for the next iterations

Oh, and [1e13,1e13] is the initial tolerance which is supposed to be arbitrarily large, so we only draw random samples from the prior.

**Comment by mjvakili** [comment]
If you find my answer convincing, can you close this issue?
