### ISSUE TITLE
Couldn't get mpirun to work with emcee sampler!

### ISSUE THREAD

**Issue by mjvakili** [mjvakili/ccppabc#5]
Don't know why! I'll fix it later.

**Comment by kilianbreathnach** [comment]
can you show how you're trying to do it and what the errors are?

**Comment by mjvakili** [comment]
yes, in this:
https://github.com/mjvakili/ccppabc/blob/master/halo/code/emcee_emcee.py,
I think the following has to run emcee with multiple cores:

    pool = MPIPool()
    if not pool.is_master():
       pool.wait()
       sys.exit(0)

    sampler = emcee.EnsembleSampler(Nwalkers, Ndim, lnprob, pool = pool)

    sampler.run_mcmc(pos, Nchains_burn + Nchains_pro)

    samples = sampler.chain[:, Nchains_burn:, :].reshape((-1, Ndim))
    #closing the pool 
    pool.close()

But it doesn't work. So now, I'm running it without pool.

**Comment by mjvakili** [comment]
Oh, and this is the error I get:

    sampler.run_mcmc(pos, Nchains_burn + Nchains_pro)
  File "/home/mj/.local/lib/python2.7/site-packages/emcee/sampler.py", line 157, in run_mcmc
    **kwargs):
  File "/home/mj/.local/lib/python2.7/site-packages/emcee/ensemble.py", line 198, in sample
    lnprob, blobs = self._get_lnprob(p)
  File "/home/mj/.local/lib/python2.7/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/home/mj/.local/lib/python2.7/site-packages/emcee/mpi_pool.py", line 154, in map
    r = self.comm.isend(F, dest=i + 1)
  File "MPI/Comm.pyx", line 1208, in mpi4py.MPI.Comm.isend (src/mpi4py.MPI.c:107276)
  File "MPI/msgpickle.pxi", line 306, in mpi4py.MPI.PyMPI_isend (src/mpi4py.MPI.c:43168)
  File "MPI/msgpickle.pxi", line 112, in mpi4py.MPI.Pickle.dump (src/mpi4py.MPI.c:40704)
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

Any idea?

**Comment by mjvakili** [comment]
I think that's b/c the likelihood function calls a class in another module (HODsim). Maybe, that messes up with picklability!

**Comment by mjvakili** [comment]
This is fixed!

**Comment by kilianbreathnach** [comment]
Was the problem the fact that the walkers were reinitialised after loading the old chain? Or the initial random guess params?

**Comment by mjvakili** [comment]
No. The thing you're refering to happened when I was restructuring the mpi part of the code. That's not the reason the code didn't work with mpi.

**Comment by kilianbreathnach** [comment]
ah, it had to do with the mpi implementation on mercer?

**Comment by mjvakili** [comment]
I think so. I haven't run the code on any other server. I guess something about the MPI installation on bbq is not quite compatible with the code. But I'm not entirely sure.
