### ISSUE TITLE
Possible bug in plot_thetas function in plotting.py

### ISSUE THREAD

**Issue by mjvakili** [mjvakili/ccppabc#6]
I get this error when I ran abc_pemcee.py

ValueError: to_rgba: Invalid rgba arg "0.682352941176"
to_rgb: Invalid rgb arg "0.682352941176"
cannot convert argument to rgb sequence

@changhoonhahn can you look at this?

**Comment by changhoonhahn** [comment]
@mjvakili aw damn it. Does corner not work with prettycolor -.- .... How are we going to get the schweet schweet colors in our plots? I'll fix it up.

**Comment by changhoonhahn** [comment]
Fixed. 

The way dfm deals with the colors is incompatible with my matplotlib color hack. I removed the pretty plotting modules along with 'prettyplotting.py'.

**Comment by mjvakili** [comment]
I yeah, I just realized that pretty color and corner are incompatible.
