### ISSUE TITLE
vim tab spacing.

### ISSUE THREAD

**Issue by changhoonhahn** [mjvakili/ccppabc#8]
@mjvakili : I think you should specify tab size in your ~\.vimrc to be consistent with python syntax. Currently it's inconsistent, so it's pretty confusing.

**Comment by mjvakili** [comment]
Ok. Actually can you send your vimrc to me so I can use whatever setrings you have?

**Comment by changhoonhahn** [comment]
Sure, I'll send it over via e-mail. Sent you messages on slack btw.
