### ISSUE TITLE
"Building lookup tables for the NFWPhaseSpace radial profile."

### ISSUE THREAD

**Issue by changhoonhahn** [mjvakili/ccppabc#9]
Whenever I do a serious mpirun with many cores, I always get the following message from halotools

...Building lookup tables for the NFWPhaseSpace radial profile.
    (This will take about 6 seconds, and only needs to be done once)

No idea what this is about, but we should probably figure out what it is.

**Comment by mjvakili** [comment]
what counts as a serious mpirun?
